format = """
[ ](white) \
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status
$character\
"""

scan_timeout = 10

[directory]
format = "[](bold cyan) [$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = " [ clairvoyidiot $symbol$branch(:$remote_branch)]($style) "
